name: weather_app
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - joblib=1.3.2
  - pytorch=2.0.1
  - cpuonly
  - pip
  - pip:
      - Flask==2.3.3
      - gunicorn==21.2.0
